POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "mAn",
    "number": "040-1235754"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Mehesantti",
    "number": "040-1234"
}

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/61f0f52cb307635fedfe516f
###

DELETE http://localhost:3001/api/persons/61fa4e348a1b44b19f7a09f7
###

PUT http://localhost:3001/api/persons/61fa4e348a1b44b19f7a09f7
content-type: application/json

{
    "number": "221121"
}

###
GET http://localhost:3001/info