POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Meaa",
    "number": "040-1235"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "testing",
    "number": "testing"
}

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/61f0f52cb307635fedfe516f
###

DELETE http://localhost:3001/api/persons/620b61e894a1139efce77a95
###

DELETE http://localhost:3001/api/all
###

PUT http://localhost:3001/api/persons/620362e9cf483a56ed04701f
content-type: application/json

{
    "number": "040-14115"
}

###
GET http://localhost:3001/info