POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Mehi",
    "number": "040-1235"
}

###

POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "me",
    "number": "040-12345"
}

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/61f0f52cb307635fedfe516f
###

DELETE http://localhost:3001/api/persons/62037a3fe9fbe9190d63d959
###

PUT http://localhost:3001/api/persons/620362e9cf483a56ed04701f
content-type: application/json

{
    "number": "040-14115"
}

###
GET http://localhost:3001/info